VBLOCKS-1211 End-to-end tests and app under "test" folder
twilio/twilio-voice-react-native pull request #110
Opened 2022-11-17 22:40 UTC by bobiechen-twilio

## Submission Checklist

 - [ ] Updated the `CHANGELOG.md` to reflect any **feature**, **bug fixes**, or **known issues** made in the source code
 - [ ] Tested code changes and observed expected behavior in the example app
 - [ ] Performed a visual inspection of the `Files changed` tab prior to submitting the pull request for review to ensure proper usage of the style guide

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Description

Moving the e2e test host app under the `/test` folder

## Breakdown

- Move and rename `test-application` to `test/app`
- Update path references

## Validation

- CircleCI

2022-11-17 22:43 UTC, mhuynh5757 commented on .circleci/config.yml
> +            cd test/app/ios && pod install && cd ../..
Do we need to `cd ../../..` since we're nested one more layer?

2022-11-17 22:44 UTC, mhuynh5757 commented
We probably should have discussed this, but since we're not moving unit tests does this PR still make sense? It seems like we're going from `test-app` to `test/app`

2022-11-17 23:02 UTC, mhuynh5757 commented on package.json
> +    "!lib/typescript/app",
```suggestion
    "!lib/typescript/test/app",
```

2022-11-17 23:02 UTC, mhuynh5757 commented on test/app/.detoxrc.json
> +}
```suggestion
}

```

2022-11-17 23:03 UTC, mhuynh5757 commented on test/app/README.md
> +- Token - Create a file, `e2e-tests-token.ts` under `app/src` directory with the following content.
```suggestion
- Token - Create a file, `e2e-tests-token.ts` under `test/app/src` directory with the following content.
```

2022-11-18 00:28 UTC, charliesantos commented
@bobiechen-twilio do we know why ios e2e test is failing?

2022-11-18 00:33 UTC, charliesantos requested changes

2022-11-18 00:33 UTC, charliesantos commented on .circleci/config.yml
>              cd ../
For all the `cd ../` commands here and below, do we need to go one more level up?

2022-11-18 00:33 UTC, charliesantos commented on test/app/README.md
> +  cd app
> cd test/app

2022-11-18 00:33 UTC, charliesantos commented on test/app/README.md
> +cd app
>cd test/app

2022-11-18 19:02 UTC, charliesantos approved these changes

2022-11-18 22:01 UTC, merged