VBLOCKS-1800 iOS incoming call flow refactor
twilio/twilio-voice-react-native pull request #179
Opened 2023-06-23 00:24 UTC by bobiechen-twilio

## Submission Checklist

 - [ ] Updated the `CHANGELOG.md` to reflect any **feature**, **bug fixes**, or **known issues** made in the source code
 - [ ] Tested code changes and observed expected behavior in the example app
 - [ ] Performed a visual inspection of the `Files changed` tab prior to submitting the pull request for review to ensure proper usage of the style guide

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Description

- [ ] Link issue links

### Problem description

- The SDK (iOS layer) intercepts all the PushKit notifications and the applications have no control over it. Some application already have PushKit logic implemented but now all notifications are redirected to the RN SDK.
- The VoIP push notification is reported to CallKit by the SDK to avoid the policy violation termination. The applications have no way of controlling the caller handle/name being reported to CallKit.

### Refactor solution

- Allow applications to opt out and use their own iOS PushKit implementation. The applications will be able to receive and control the push notifications they receive, especially if they have other modules also depending on push notifications. The `Voice.initializePushRegistry()` method will allow the app to delegate this back to the SDK.
- A new method `Voice.handlePushNotification()` for the applications to pass the push payload to the SDK, if the platform push notification module is implemented outside of the SDK. `CallInvite` event will be returned as it is already doing.
- A new method `Voice.reportNewIncomingCall()` for the iOS applications to report to CallKit, with the flexibility to determine the caller name instead of the SDK using the `from` value of the call invite. For Android applications, this is not required.

## Breakdown

- [Bulleted summary of changes]
- [eg. Updated documentation]
- [eg. Added audio device feature]

## Validation

-

2023-06-27 20:40 UTC, bobiechen-twilio commented
from the discussion:
- document the values in the call invite
- implement voice_handlePushNotification() for Android
  - [ ] create a ticket for Android specific task
- leave CallInvite.reportNewIncomingCall() for later

2023-08-03 20:52 UTC, charliesantos commented on api/voice-react-native-sdk.api.md
> +    initializePushRegistry(): Promise<void>;
Do we need to update IDL?

2023-08-09 23:04 UTC, mhuynh5757 approved these changes

2023-08-09 23:04 UTC, mhuynh5757 commented on ios/docs/applications-own-pushkit-handler.md
> +Upon getting the PushKit device token update, post a notification and include the device token (in the form of `NSData`) in the `userInfo`. The device token will later be used when calling the `Voice
```suggestion
Upon receiving the PushKit device token update, post a notification and include the device token (in the form of `NSData`) in the `userInfo`. The device token will later be used when calling the `Voice.register()` method.
```

2023-08-09 23:04 UTC, mhuynh5757 commented on ios/docs/applications-own-pushkit-handler.md
> +### Reporting new incoming call to iOS CallKit
```suggestion
### Reporting a new incoming call to iOS CallKit
```

2023-08-09 23:05 UTC, mhuynh5757 requested changes
Apologies, misclicked the Approve button. I had minor comments, but I think they should be addressed.

2023-08-09 23:20 UTC, bobiechen-twilio commented on ios/TwilioVoicePushRegistry.m
> +NSString * const kTwilioVoicePushRegistryNotificationDeviceToken = @"deviceToken";
The string literal `deviceToken` is only used in the iOS so I guess it's fine to keep it in the iOS layer.

2023-08-09 23:21 UTC, bobiechen-twilio commented on ios/TwilioVoiceReactNative.m
> +    [self initializePushRegistry];
Good point, but the iOS PushKit initialization seems to be a fire and forget op. Doesn't seem to be a way to know things went wrong.

2023-08-10 00:19 UTC, mhuynh5757 commented on ios/TwilioVoiceReactNative.m
> +    [self initializePushRegistry];
LOL, okay well that's concerning but nothing we can do about it 🤷

2023-08-10 00:22 UTC, mhuynh5757 requested changes

2023-08-10 00:22 UTC, mhuynh5757 commented on src/Voice.tsx
> +   Unsupported platforms:
Sorry, I missed the prefix `*` characters in the last review.

2023-08-10 23:33 UTC, mhuynh5757 approved these changes

2023-08-10 23:40 UTC, merged