[VBLOCKS-1913] Persist extra call info
twilio/twilio-voice-react-native pull request #197
Opened 2023-08-02 20:23 UTC by mhuynh5757

## Submission Checklist

 - [ ] Updated the `CHANGELOG.md` to reflect any **feature**, **bug fixes**, or **known issues** made in the source code
 - [ ] Tested code changes and observed expected behavior in the example app
 - [ ] Performed a visual inspection of the `Files changed` tab prior to submitting the pull request for review to ensure proper usage of the style guide

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Description

[Description of the Pull Request]

## Breakdown

- [Bulleted summary of changes]
- [eg. Updated documentation]
- [eg. Added audio device feature]

## Validation

- [Bulleted summary of validation steps]
- [eg. Added new test]
- [eg. Manually tested with app]

## Additional Notes

[Any additional comments, notes, or information relevant to reviewers.]

2023-08-03 20:36 UTC, charliesantos requested changes
Do we need to write tests?

2023-08-03 20:42 UTC, charliesantos commented on api/voice-react-native-sdk.api.md
> +    getInitialConnectedTimestamp(): number | undefined;
This is a new public API right? This is not too big of an example, but I think we need to get into the habit of following our process for any new public APIs. If the changes requires new/updated API:
- Create/update IDL and get it reviewed, before implementing into the SDK
- Check other voice SDKs answer questions like
  - Is this applicable to other voice sdks?
  - Do we need to add similar feature?
  - How is this done on other voice sdks, if applicable?
- Probably not applicable in this PR but also part of the process. If the new feature or API is complex enough
  - Create a design doc
  - Review with the team

2023-08-03 21:54 UTC, mhuynh5757 commented
Good catch regarding tests @charliesantos, they slipped my mind. The coverage is back to (almost) 100. Please take another look.

2023-08-03 21:56 UTC, charliesantos approved these changes

2023-08-07 19:47 UTC, afalls-twilio approved these changes

2023-08-07 23:54 UTC, kpchoy approved these changes

2023-08-08 18:26 UTC, bobiechen-twilio commented on ios/TwilioVoiceReactNative+CallKit.m
> +    NSNumber *timeStampObj = [NSNumber numberWithDouble: timeStamp];
Remove space between `numberWithDouble:` and `timeStamp`

2023-08-08 18:28 UTC, bobiechen-twilio approved these changes
A small suggestion but feel free to merge after removing the extra space.

2023-08-08 22:51 UTC, merged