[VBLOCKS-2017] Notification tapped event
twilio/twilio-voice-react-native pull request #198
Opened 2023-08-03 00:25 UTC by mhuynh5757

## Submission Checklist

 - [ ] Updated the `CHANGELOG.md` to reflect any **feature**, **bug fixes**, or **known issues** made in the source code
 - [ ] Tested code changes and observed expected behavior in the example app
 - [ ] Performed a visual inspection of the `Files changed` tab prior to submitting the pull request for review to ensure proper usage of the style guide

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Description

[Description of the Pull Request]

## Breakdown

- [Bulleted summary of changes]
- [eg. Updated documentation]
- [eg. Added audio device feature]

## Validation

- [Bulleted summary of validation steps]
- [eg. Added new test]
- [eg. Manually tested with app]

## Additional Notes

[Any additional comments, notes, or information relevant to reviewers.]

2023-08-03 20:48 UTC, charliesantos requested changes
This is only supported on android correct? Do we have a standard way in our docs that shows SDK users what platforms are supported?
Also, if I use this event on iOS, what's going to happen? Any warnings, errors?

2023-08-03 20:49 UTC, charliesantos reviewed
Same as my comment in the other PR https://github.com/twilio/twilio-voice-react-native/pull/197#discussion_r1283700190
>This is not too big of an example, but I think we need to get into the habit of following our process for any new public APIs.

2023-08-03 21:17 UTC, mhuynh5757 commented
There's no standard way to denote this as a platform specific API at the moment. If you check out the docstring for something like ```
/**
   * Show the native AV route picker.
   *
   * @remarks
   * This API is specific to iOS and unavailable in Android. If this API is
   * invoked on Android, there will be no operation and the returned `Promise`
   * will immediately resolve with `null`.
   *
   * @returns
   * A `Promise` that
   *  - Resolves when the AV Route Picker View is shown.
   */
  showAvRoutePickerView(): Promise<void> {
    return NativeModule.voice_showNativeAvRoutePicker();
  }
``` this is typically how we've done it, but i think there's a lot of room for improvement

2023-08-03 21:47 UTC, charliesantos approved these changes

2023-08-07 18:03 UTC, kpchoy approved these changes

2023-08-07 18:07 UTC, afalls-twilio approved these changes

2023-08-07 19:31 UTC, merged