VBLOCKS-2560: Migration guide for beta.4 release
twilio/twilio-voice-react-native pull request #274
Opened 2024-01-10 23:33 UTC by afalls-twilio

## Submission Checklist

 - [x] Updated the `CHANGELOG.md` to reflect any **feature**, **bug fixes**, or **known issues** made in the source code
 - [ ] Tested code changes and observed expected behavior in the example app
 - [ ] Performed a visual inspection of the `Files changed` tab prior to submitting the pull request for review to ensure proper usage of the style guide

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Description

Added a migration guide for the up coming beta.4 release.

## Breakdown

- Added migration guide for beta.4 release
- Updated changelog

## Validation

n/a

## Additional Notes

None

2024-01-10 23:41 UTC, mhuynh5757 requested changes
Are the suggestions correct? I recall the methods being camelCased and not PascalCased.

2024-01-10 23:41 UTC, mhuynh5757 commented on docs/migration-guide-beta.4.md
> +Services, BroadcastReceivers, or additional Activities were added to the SDK. this is no longer the
```suggestion
Services, BroadcastReceivers, or additional Activities were added to the SDK. This is no longer the 
```

2024-01-10 23:41 UTC, mhuynh5757 commented on docs/migration-guide-beta.4.md
> +either the constructor (not in the `OnCreate(...)` method). Then, the following activity methods
```suggestion
either the constructor (not in the `onCreate(...)` method). Then, the following activity methods
```

2024-01-10 23:41 UTC, mhuynh5757 commented on docs/migration-guide-beta.4.md
> +need to be overridden, `OnCreate(...)`, `OnDestroy(...)` and `onNewIntent(...)`. In the
```suggestion
need to be overridden, `onCreate(...)`, `onDestroy(...)` and `onNewIntent(...)`. In the 
```

2024-01-10 23:41 UTC, mhuynh5757 commented on docs/migration-guide-beta.4.md
> +`android.app.Application` methods need to be overridden, `OnCreate(...)` & `OnTerminate(...)`. In
```suggestion
`android.app.Application` methods need to be overridden, `onCreate(...)` & `onTerminate(...)`. In
```

2024-01-10 23:43 UTC, charliesantos approved these changes

2024-01-11 00:47 UTC, mhuynh5757 approved these changes

2024-01-11 00:47 UTC, afalls-twilio commented on docs/migration-guide-beta.4.md
> +`android.app.Application` methods need to be overridden, `OnCreate(...)` & `OnTerminate(...)`. In
yeah, you are correct!

2024-01-11 02:46 UTC, merged