[VBLOCKS-2797] Rebase user defined messages
twilio/twilio-voice-react-native pull request #326
Opened 2024-03-01 01:06 UTC by mhuynh5757

## Submission Checklist

 - [x] ~Updated the `CHANGELOG.md` to reflect any **feature**, **bug fixes**, or **known issues** made in the source code~
 - [x] Tested code changes and observed expected behavior in the example app
 - [x] Performed a visual inspection of the `Files changed` tab prior to submitting the pull request for review to ensure proper usage of the style guide

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Description

This PR makes a merge commit from main to the user defined messages feature branch.

## Breakdown

- Merge main into feature branch.
- Resolve some merge conflicts and use patterns from main instead of the feature branch.

## Validation

- Went through unit tests and wrote new ones using patterns from main.
- Removed old unit tests.
- Manual testing on iOS and Android.

## Additional Notes

N/A

2024-03-01 22:12 UTC, kpchoy requested changes

2024-03-01 22:12 UTC, kpchoy commented on src/CallInvite.tsx
> +     * See {@link (Call:interface).(addListener:1)}.
```suggestion
     * See {@link (CallInvite:interface).(addListener:1)}.
```

2024-03-01 22:12 UTC, kpchoy commented on src/CallInvite.tsx
> +     * See {@link (Call:interface).(addListener:3)}.
Same as above, should this be `CallInvite:interface`

2024-03-01 22:12 UTC, kpchoy commented on src/CallInvite.tsx
> +     * See {@link (Call:interface).(addListener:4)}.
Same as above, should this be `CallInvite:interface`

2024-03-01 22:15 UTC, mhuynh5757 commented on src/CallInvite.tsx
> +   * ```typescript
Good point, I'll add it for clarity's sake.

2024-03-01 22:15 UTC, mhuynh5757 commented
Good catch with the docstrings.

2024-03-05 01:11 UTC, kpchoy approved these changes
LGTM

2024-03-06 19:29 UTC, kpchoy commented on src/CallInvite.tsx
> +   *   callInvite.on(CallInvite.Event.Cancelled, () => {
Do you want to add error here as argument?
```suggestion
   *   callInvite.on(CallInvite.Event.Cancelled, (error) => {
```

2024-03-06 19:29 UTC, kpchoy commented on src/CallInvite.tsx
> +   *   callInvite.on(CallInvite.Event.Accepted, () => {
Do you want to add `call` here as argument? 
```suggestion
   *   callInvite.on(CallInvite.Event.Accepted, (call) => {
```

2024-03-06 22:31 UTC, kpchoy approved these changes

2024-03-06 22:53 UTC, merged